/* Generated By:JavaCC: Do not edit this line. simplejavaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface simplejavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int CLASS = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int NEW = 20;
  /** RegularExpression Id. */
  int PLUS = 21;
  /** RegularExpression Id. */
  int SEMICOLON = 22;
  /** RegularExpression Id. */
  int MINUS = 23;
  /** RegularExpression Id. */
  int TIMES = 24;
  /** RegularExpression Id. */
  int DIVIDE = 25;
  /** RegularExpression Id. */
  int EQUAL = 26;
  /** RegularExpression Id. */
  int GREATER_THAN = 27;
  /** RegularExpression Id. */
  int NOT = 28;
  /** RegularExpression Id. */
  int LEFT_BRACE = 29;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 30;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 31;
  /** RegularExpression Id. */
  int PERIOD = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int GREATER_THAN_OR_EQUAL_TO = 34;
  /** RegularExpression Id. */
  int AND = 35;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 36;
  /** RegularExpression Id. */
  int LEFT_PARENTHESIS = 37;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESIS = 38;
  /** RegularExpression Id. */
  int NOT_EQUAL = 39;
  /** RegularExpression Id. */
  int LESS_THAN_OR_EQUAL_TO = 40;
  /** RegularExpression Id. */
  int LESS_THAN = 41;
  /** RegularExpression Id. */
  int GETS = 42;
  /** RegularExpression Id. */
  int OR = 43;
  /** RegularExpression Id. */
  int ADD = 44;
  /** RegularExpression Id. */
  int MINUSMINUS = 45;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 46;
  /** RegularExpression Id. */
  int IDENTIFIER = 47;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\\\t\"",
    "\"\\t\"",
    "\"EOF\"",
    "\"\\n\"",
    "\"/*\"",
    "<token of kind 7>",
    "\"*/\"",
    "\"/*\"",
    "<token of kind 10>",
    "\"else\"",
    "\"for\"",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"class\"",
    "\"true\"",
    "\"false\"",
    "\"return\"",
    "\"new\"",
    "\"+\"",
    "\";\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"==\"",
    "\">\"",
    "\"!\"",
    "\"{\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\",\"",
    "\">=\"",
    "\"&&\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"!=\"",
    "\"<=\"",
    "\"<\"",
    "\"=\"",
    "\"||\"",
    "\"++\"",
    "\"--\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
  };

}
